import App

let app = App()
do {
    try app.run()
} catch {
    print("Error Occured: \(error)")
}


